### ISSUE TITLE
Richard: Don't check in commented out code to master branch

### ISSUE THREAD

**Issue by eric-do** [Twobular/product-detail-page#20]
https://github.com/Twobular/product-detail-page/blob/6c0bf1c60e0c93a69b82a86393f47892b7cb0519/client/src/components/OView/ImageSlider.jsx#L32

Get out of the habit of commenting out code and then checking it in to production. Instead, make a commit and check out a separate branch. If you need to go back to the "commented" out code, just discard that branch and go to the previous branch.

**Comment by richardyu3** [comment]
Resolved.
