### ISSUE TITLE
Richard: clean up code spacing

### ISSUE THREAD

**Issue by eric-do** [Twobular/product-detail-page#21]
https://github.com/Twobular/product-detail-page/blob/6c0bf1c60e0c93a69b82a86393f47892b7cb0519/client/src/components/OView/Overview.jsx#L145

One of the first clear indicators of inexperience is inconsistent line spacing. Sometimes you have 2, sometimes 3, sometimes 1. Keep your code compact and easy to read.

**Comment by richardyu3** [comment]
Resolved.
