### ISSUE TITLE
Richard: structure your code with variable declarations at the top

### ISSUE THREAD

**Issue by eric-do** [Twobular/product-detail-page#22]
https://github.com/Twobular/product-detail-page/blob/6c0bf1c60e0c93a69b82a86393f47892b7cb0519/client/src/components/OView/Overview.jsx#L158

Your code could use more structure. Generally we want to keep declarations at the top, followed by logic such as loops.

Your useState declarations - if they're not dependent on anything above them, should also go at the top

**Comment by richardyu3** [comment]
Resolved.
