### ISSUE TITLE
Richard: avoid having long unbroken lines

### ISSUE THREAD

**Issue by eric-do** [Twobular/product-detail-page#23]
https://github.com/Twobular/product-detail-page/blob/6c0bf1c60e0c93a69b82a86393f47892b7cb0519/client/src/components/OView/Overview.jsx#L227

Readers of your code shouldn't need to read both vertically and horizontally. It's easier to just go with vertically.

For components with many attributes, put each one on its own line, e.g.
```javascript
<ImageSlider
    objSlideToContinueFrom={slideToContinueFrom} 
    startFromBeginning={true} 
    currentGroupOfImageURLs={currentGroupOfImageURLs} 
    handleClickProductImageDiv={handleClickProductImageDiv} 
    resetSliderForExpandedView={true} 
    key={Date.now()}
/>
```

**Comment by richardyu3** [comment]
Resolved.
