### ISSUE TITLE
Eddie: try to apply styled-components to most/all tags

### ISSUE THREAD

**Issue by eric-do** [Twobular/product-detail-page#28]
https://github.com/Twobular/product-detail-page/blob/6c0bf1c60e0c93a69b82a86393f47892b7cb0519/client/src/components/QuestionsAndAnswers/Modal.jsx#L57

Even if the tag itself doesn't require styling, you can still just do something like
```
const AnswerContainer = styled.div``;
const Label = styled.label``;
```

One of the benefits of Styled Components is that it abstracts away code. Readers of your code can have a good idea of the structure of your component because the all the HTML tags are now descriptive styled components.

**Comment by ElRemolino** [comment]
Got it! Thanks for the feedback Eric!
