### ISSUE TITLE
Eddie: 'searchTerm' is not being used?

### ISSUE THREAD

**Issue by eric-do** [Twobular/product-detail-page#30]
https://github.com/Twobular/product-detail-page/blob/3ab9459c3d9933f238850d9ea5ff242d518d6a0c/client/src/components/QuestionsAndAnswers/SearchBar.jsx#L14

I see a searchTerm variable here but it's not being used in your input field? Typically there should be a 'value' attribute that points to the state that contains the display value, i.e.

```javascript
const [searchTerm, setTerm] = useState('');

const handleInput = e => {...} // you have this already

return (
  <input
    onChange={handleInput}
    value={searchTerm}
  />
)
```

I'm only looking at code, not running it, so close this if this is outdated or you have some other workaround.

**Comment by ElRemolino** [comment]
I did have a work around but I think it makes more sense to do what you suggested
